name: ci
run-name: build packages on all platforms
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-x86_64-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix run

  build-aarch64-linux:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix run

  build-x86_64-darwin:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            sandbox = true
      - run: nix run

  build-aarch64-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            sandbox = true
      - run: nix run
